{
 "title": "suricata - IDS & IPS",
 "description": "Surricata, IDS/IPS",
 "tags": [
  "IDS",
  "IPS",
  "Proxmox"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "attack",
    "query": "{\"find\": \"terms\", \"field\":\"suricata.eve.alert.signature\",\"size\":\"1000\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Ataque mais usado",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "suricata.eve.alert.signature",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND suricata.eve.event_type:\"alert\", \"drop\", \"reject\", \"pass\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "País que mais atacou",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND suricata.eve.event_type:\"alert\", \"drop\", \"reject\", \"pass\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IP que mais atacou",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND _exists_:source.ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mapa de Origem de Ataques",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "source.geo.location", "id": "3", "settings": { "precision": "3" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND _exists_:source.geo.location",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Países",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND suricata.eve.event_type:\"alert\", \"drop\", \"reject\", \"pass\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tipos de ataques",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "suricata.eve.alert.signature",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND suricata.eve.event_type:\"alert\", \"drop\", \"reject\", \"pass\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Categoria de ataque",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "suricata.eve.alert.category",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND _exists_:suricata.eve.alert.category",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Portas",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.port",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND _exists_:destination.port",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Histórico de ataques",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event.dataset:\"suricata.eve\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Detalhes dos Ataques",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event.dataset:\"suricata.eve\" AND event.kind:(alert OR drop OR reject OR pass) AND _exists_:source.as.number",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}